SELECT MAX(AGE) FROM CUSTOMER

SELECT MIN(AGE) FROM CUSTOMER

SELECT MIN(BILL_AMOUNT) FROM CUSTOMER

SELECT COUNT(CUSTOMER_NAME) FROM CUSTOMER

SELECT SUM(BILL_AMOUNT) FROM CUSTOMER

SELECT AVG(AGE) FROM CUSTOMER WHERE GENDER = 'Female'