UPDATE CUSTOMER
SET PHONE_NUMBER = 753951
WHERE CUSTOMER_NAME = 'Ramya';
UPDATE CUSTOMER
SET CUSTOMER_NAME = 'Rohit Kumar'
WHERE CUSTOMER_ID = 8;
UPDATE CUSTOMER
SET AGE = 16, BILL_AMOUNT = 1300
WHERE CUSTOMER_ID = 4;

commit