SELECT PERSON_NAME,MARKS,
(CASE WHEN MARKS >= 85 THEN 'Distinction'
WHEN MARKS < 35 THEN 'Fail'
ELSE 'Pass'
END) AS RESULTS
FROM PERSON;

SELECT PERSON_NAME,WEIGHT,
(CASE WHEN WEIGHT >=80 THEN 'Over Weight'
WHEN WEIGHT <= 50 THEN 'Under Weight'
ELSE 'NORMAL WEIGHT'
END
) AS WEIGHT_CHECK
FROM PERSON;

SELECT PERSON_NAME,BANKID,
(CASE WHEN BANKID = 1 THEN 'HDFC BANK'
WHEN BANKID = 2 THEN 'ICICI BANK'
WHEN BANKID = 3 THEN 'SBI BANK'
WHEN BANKID = 4 THEN 'KOTAK BANK'
ELSE 'OTHER BANK'
END) AS BANK_NAME --This case statement is used to display the BANK NAME
FROM PERSON;

SELECT PERSON_NAME,
DECODE(BANKID,1,'HDFC BANK',2,'ICICI BANK',3,'SBI BANK',4,'KOTAK BANK','OTHER BANK') AS BANK_NAME
FROM PERSON;