create table books
( bookid number NOT NULL,
bookname varchar2(100)
);

insert into books values (10,'Ramayana')

insert into books values(NULL,'Panchatantra')

ALTER TABLE BOOKS
MODIFY bookname varchar2(100) NOT NULL;

INSERT INTO BOOKS VALUES (20,NULL)

DROP TABLE BOOKS

CREATE TABLE BOOKS
( BOOKID NUMBER NOT NULL UNIQUE,
BOOKNAME VARCHAR2(100)
);

SELECT * FROM BOOKS

INSERT INTO BOOKS VALUES (10,'Ramayana')

insert into books values (20,'Panchatantra')

alter table books
modify bookname varchar2(100) NOT NULL UNIQUE;

insert into books values (30,'Tinkle')

DROP TABLE BOOKS

CREATE TABLE BOOKS
( BOOKID NUMBER NOT NULL,
BOOKNAME VARCHAR2(100),
CONSTRAINT PK_BOOKID PRIMARY KEY (BOOKID)
);

INSERT INTO BOOKS VALUES (10,'Ramayana')

INSERT INTO BOOKS VALUES (20,'Panchatantra')

INSERT INTO BOOKS VALUES (null,'Ramayana')

ALTER TABLE BOOKS
ADD CONSTRAINT PK_BOOKID PRIMARY KEY(BOOKID);


CREATE TABLE BOOKS
( BOOKID NUMBER NOT NULL,
BOOKNAME VARCHAR2(100),
CUSTOMERID NUMBER,
CONSTRAINT PK_BOOKID PRIMARY KEY (BOOKID),
CONSTRAINT FK_CUTOMERID FOREIGN KEY(CUSTOMERID)
REFERENCES CUSTOMER(CUSTOMER_ID)
);

ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_CUSTOMERID PRIMARY KEY(CUSTOMER_ID);

INSERT INTO BOOKS VALUES(10,'Ramayana',1);
INSERT INTO BOOKS VALUES(20,'Panchatantra',2);
INSERT INTO BOOKS VALUES(30,'Tinkle',2)

select bookid,bookname,customer_name from books,customer
where books.customerid = customer.customer_id


CREATE TABLE BOOKS
( BOOKID NUMBER NOT NULL,
BOOKNAME VARCHAR2(100),
BOOKPRICE NUMBER,
CONSTRAINT CH_BOOKPRICE CHECK (BOOKPRICE > 10)
);

INSERT INTO BOOKS VALUES (10,'Ramayana','50')

insert into books values (20,'Panchatantra',11)

CREATE TABLE BOOKS
( BOOKID NUMBER NOT NULL,
BOOKNAME VARCHAR2(100),
BOOKPRICE NUMBER DEFAULT 20
);

INSERT INTO BOOKS VALUES (10,'Ramayana',50)

INSERT INTO BOOKS VALUES (10,'Panchatantra',DEFAULT)

CREATE UNIQUE INDEX BOOKID_I1
ON books(bookid)

DROP INDEX BOOKID_I1